#!/usr/bin/env bash
# Configures Nginx for URL redirection

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

redirection="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=Htqn7tGvQsc permanent;"
sudo sed -i "s/server_name _;/$redirection/" /etc/nginx/sites-enabled/default


sudo service nginx restart
