#!/usr/bin/env bash
# Install and configure HAProxy load balancer

sudo apt-get -y update
sudo apt-get -y install haproxy

sudo cp /etc/haproxy/haproxy.cfg haproxy_default.backup

config=\
"
defaults
        mode http
        timeout client 15s
        timeout connect 10s
        timeout server 15s
        timeout http-request 10s
frontend hallomer_frontend
        bind *:80
        default_backend hallomer_backend
backend hallomer_backend
        balance roundrobin
        server 513189-web-01 100.25.197.112:80 check
        server 513189-web-02 34.224.4.126:80 check
"
echo "$config" | sudo tee -a /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy


sudo haproxy -c -f /etc/haproxy/haproxy.cfg

sudo service haproxy restart
