#!/usr/bin/env bash
# Does a lot of things.

terminate() {
    echo "$1"
    rm -f /var/run/myscript.pid
    exit
}
echo $$ > /var/run/myscript.pid
trap 'terminate "I hate the kill command"' SIGTERM
trap 'terminate "Y U no love me?!"' SIGINT
trap 'terminate ""' SIGQUIT
while true; do
    echo "To infinity and beyond"
    sleep 2
done
