#!/usr/bin/env bash
# Manages manage_my_process.

case "$1"in
    start)
        ./manage_my_process &
        echo "$!" > /var/run/my_process.pid
        echo "manage_my_process started"
        ;;
    stop)
        pgrep -f manage_my_process | xargs kill
        rm /var/run/my_process.pid
        echo "manage_my_process stopped"
        ;;
    restart)
        pgrep -f manage_my_process | xargs kill
        rm /var/run/my_process.pid
        ./manage_my_process &
        echo "$!" > /var/run/my_process.pid
        echo "manage_my_process restarted"
        ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        exit 1
        ;;
esac
exit 0
