#!/usr/bin/env bash
# This script displays the content of the file /etc/passwd with a story

file="/etc/passwd"
while IFS=':' read -r usr pass id gid info home cmd
do
    echo "The user $usr is part of the $gid gang, lives in $home and rides $cmd. $id's place is protected by the passcode $pass, more info about the user here: $info"
done < "$file"
