#!/usr/bin/env bash
# This script displays IP with HTTP status code from the Apache log file with number of occurrences

file="apache-access.log"
awk '{ print $1, $9 }' "$file" | sort | uniq -c | sort -rn
