#!/usr/bin/env bash
# This script displays "Best School" 10 times and "Hi" on the 9th iteration
i=0
while [ $i -le 9 ]
do
    echo "Best School"
    ((i++))
    if [ $i -eq 9 ]; then
        echo "Hi"
    fi
done
