#!/usr/bin/env bash
# This script configures an Ubuntu server with the task requirement
cp /etc/hosts ~/hosts.new
sed -i '/localhost/d' ~/hosts.new
echo "127.0.0.2 localhost" >> ~/hosts.new
sed -i '/facebook.com/d' ~/hosts.new
echo "8.8.8.8 facebook.com" >> ~/hosts.new
sudo cp -f ~/hosts.new /etc/hosts
