#!/usr/bin/env bash
# This script configures an Ubuntu server with the task requirement
cp /etc/hosts ~/hosts.new
sed -i 's/localhost/127.0.0.2/' ~/hosts.new
sed -i 's/facebook.com/8.8.8.8/' ~/hosts.new
sudo cp -f ~/hosts.new /etc/hosts
