#!/usr/bin/env bash
# Configures Nginx to run as the 'nginx' user and listen on port 8080
sudo sed -i 's/user .*/user nginx;/g' /etc/nginx/nginx.conf
sudo sed -i 's/listen 80;/listen 8080;/g'  /etc/nginx/sites-available/default
sudo service nginx restart
